### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
!pip install tensorflow-gpu

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'


  error: subprocess-exited-with-error
  
  Getting requirements to build wheel did not run successfully.
  exit code: 1
  
  [58 lines of output]
  Traceback (most recent call last):
    File "C:\Users\bhong\AppData\Local\Temp\pip-build-env-kxlkb2by\overlay\Lib\site-packages\setuptools\_vendor\packaging\requirements.py", line 36, in __init__
      parsed = _parse_requirement(requirement_string)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\bhong\AppData\Local\Temp\pip-build-env-kxlkb2by\overlay\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 62, in parse_requirement
      return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\bhong\AppData\Local\Temp\pip-build-env-kxlkb2by\overlay\Lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 80, in _parse_requirement
      url, specifier, marker = _parse_requirement_details(tokenizer)
    

In [3]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [4]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[270, 37, 398, 258], [270, 37, 398, 94], [270, 34, 398, 128], [56, 225, 188, 336, 141], [56, 225, 188, 336, 267], [56, 270, 184, 398, 317], [306, 338, 94, 336]]


### Word Embedding Represntation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 270  37 398 258]
 [  0   0   0   0 270  37 398  94]
 [  0   0   0   0 270  34 398 128]
 [  0   0   0  56 225 188 336 141]
 [  0   0   0  56 225 188 336 267]
 [  0   0   0  56 270 184 398 317]
 [  0   0   0   0 306 338  94 336]]


In [12]:
## 10 feature dimesnions
dim=10


In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

C:\Users\bhong\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 270,  37, 398, 258])

In [16]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 431ms/step


array([[ 0.03987734,  0.04609909,  0.02244625, -0.00542557,  0.02433008,
         0.04827127, -0.01565089, -0.01022401,  0.0150688 ,  0.04679796],
       [ 0.03987734,  0.04609909,  0.02244625, -0.00542557,  0.02433008,
         0.04827127, -0.01565089, -0.01022401,  0.0150688 ,  0.04679796],
       [ 0.03987734,  0.04609909,  0.02244625, -0.00542557,  0.02433008,
         0.04827127, -0.01565089, -0.01022401,  0.0150688 ,  0.04679796],
       [ 0.03987734,  0.04609909,  0.02244625, -0.00542557,  0.02433008,
         0.04827127, -0.01565089, -0.01022401,  0.0150688 ,  0.04679796],
       [ 0.00559562, -0.02296668,  0.04286214,  0.01818265,  0.01155274,
        -0.00399499,  0.04241506,  0.01884772, -0.00817076, -0.0487236 ],
       [ 0.0438221 , -0.0008656 , -0.00052249,  0.04771031, -0.04164009,
        -0.00611261, -0.00869145, -0.04688502, -0.01276709, -0.0316098 ],
       [-0.00185873,  0.00961162, -0.01851965,  0.0089551 ,  0.03960344,
         0.00447065,  0.00953121, -0.01931057

In [17]:
print(model.predict(embedded_docs))

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>

In [ ]:
embedded_docs[0]

In [ ]:
print(model.predict(embedded_docs)[0])

In [ ]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]